### ISSUE TITLE
TestMain in sdl_test.go runs with all tests (as it is run first) meaning SDL needs to work ...

### ISSUE THREAD

**Issue by sh1670** [UoB-CSA/gol-skeleton#4]
Think it might be better if we can move code which launches SDL windows outside this method as it may hamper early testing. Could even only use this test ourselves for testing?

**Comment by TBExtent** [comment]
This is (semi) fixed on the dev branch. SDL window only launches when a test requests it. It still needs to run in TestMain because SDL doesn't work outside of the main thread for some reason.

**Comment by TBExtent** [comment]
Fixed by Orchard's rewrite. SDL window defaults to not opening, and using an internal representation of the window's state
